from typing import Final

NUM_BANKS = 6
GRID_SIZE = 6
NUM_PADS = GRID_SIZE**2
NUM_SAMPLES = NUM_PADS * NUM_BANKS

# Audio
SPEED_MIN = 0.5
SPEED_MAX = 2.0
SPEED_STEP = 0.01
PITCH_BPM_STEP = 0.1
PITCH_BPM_COARSE_STEPS = 10
VOLUME_MIN = 0.0
VOLUME_MAX = 1.0

# Per-pad mixing
PAD_GAIN_MIN = 0.0
PAD_GAIN_MAX = 1.0
PAD_EQ_DB_MIN = -60.0
PAD_EQ_DB_MAX = 6.0

# Offline Demucs stem generation
DEFAULT_DEMUCS_SHIFTS = 4
MIN_DEMUCS_SHIFTS = 1
MAX_DEMUCS_SHIFTS = 20
DEFAULT_DEMUCS_OVERLAP = 0.5
MIN_DEMUCS_OVERLAP = 0.25
MAX_DEMUCS_OVERLAP = 0.95

# Real-time Key Lock DSP
DEFAULT_KEY_LOCK_QUALITY: Final = "high"
DEFAULT_KEY_LOCK_DELAY_MIN_SAMPLES = 64.0
MIN_KEY_LOCK_DELAY_MIN_SAMPLES = 16.0
MAX_KEY_LOCK_DELAY_MIN_SAMPLES = 512.0
DEFAULT_KEY_LOCK_DELAY_RANGE_SAMPLES = 1536.0
MIN_KEY_LOCK_DELAY_RANGE_SAMPLES = 256.0
MAX_KEY_LOCK_DELAY_RANGE_SAMPLES = 1984.0
MAX_KEY_LOCK_DELAY_TOTAL_SAMPLES = 2032.0
DEFAULT_KEY_LOCK_HEAD_COUNT = 2
MIN_KEY_LOCK_HEAD_COUNT = 2
MAX_KEY_LOCK_HEAD_COUNT = 4
DEFAULT_KEY_LOCK_INTERPOLATION: Final = "cubic"
DEFAULT_KEY_LOCK_WINDOW: Final = "hann"
DEFAULT_KEY_LOCK_SMOOTHING_STEP = 0.05
MIN_KEY_LOCK_SMOOTHING_STEP = 0.01
MAX_KEY_LOCK_SMOOTHING_STEP = 0.10
DEFAULT_KEY_LOCK_OUTPUT_GAIN = 1.0
MIN_KEY_LOCK_OUTPUT_GAIN = 0.25
MAX_KEY_LOCK_OUTPUT_GAIN = 2.0
