NUM_BANKS = 6
GRID_SIZE = 6
NUM_PADS = GRID_SIZE**2
NUM_SAMPLES = NUM_PADS * NUM_BANKS

# Audio
SPEED_MIN = 0.5
SPEED_MAX = 2.0
SPEED_STEP = 0.01
PITCH_BPM_STEP = 0.1
PITCH_BPM_COARSE_STEPS = 10
VOLUME_MIN = 0.0
VOLUME_MAX = 1.0

# Per-pad mixing
PAD_GAIN_DB_MIN = -60.0
PAD_GAIN_DB_MAX = 12.0
PAD_GAIN_DB_DEFAULT = 0.0
PAD_GAIN_NORMALIZED_MIN = 0.0
PAD_GAIN_NORMALIZED_CENTER = 0.5
PAD_GAIN_NORMALIZED_MAX = 1.0
PAD_GAIN_FINE_STEP_DB = 0.1
PAD_EQ_DB_MIN = -60.0
PAD_EQ_DB_MAX = 6.0
PAD_LOOP_BARS_DEFAULT = 8.0
PAD_LOOP_BARS_MIN = 0.5
PAD_LOOP_BARS_GRANULARITY = 0.5

# Offline Demucs stem generation
DEFAULT_DEMUCS_SHIFTS = 1
MIN_DEMUCS_SHIFTS = 1
MAX_DEMUCS_SHIFTS = 20
DEFAULT_DEMUCS_OVERLAP = 0.5
MIN_DEMUCS_OVERLAP = 0.25
MAX_DEMUCS_OVERLAP = 0.95
