[package]
name = "flitzis-looper-analysis"
version = "0.1.0"
edition = "2024"

[lib]
name = "flitzis_looper_analysis"

[dependencies]
matrixmultiply = "0.3"
num-complex = "0.4"
ort = "2.0.0-rc.12"
realfft = "3.4"
rubato = "0.14"
rustfft = "6.2"

[dev-dependencies]
serde_json = "1"
symphonia = { version = "0.5", features = ["all", "opt-simd", "default"] }
