"""
Core module for flitzis_looper.
Contains state management, configuration, and core logic.
"""

# Import from submodules for re-export
from flitzis_looper.core.state import (
    # Constants
    GRID_SIZE,
    NUM_BANKS,
    STEM_NAMES,
    STEM_LABELS,
    COLOR_BG,
    COLOR_BTN_INACTIVE,
    COLOR_BTN_ACTIVE,
    COLOR_TEXT,
    COLOR_TEXT_ACTIVE,
    COLOR_LOCK_OFF,
    COLOR_LOCK_ON,
    COLOR_RESET_RED,
    COLOR_BANK_BTN,
    COLOR_BANK_ACTIVE,
    COLOR_STEM_INACTIVE,
    COLOR_STEM_AVAILABLE,
    COLOR_STEM_SELECTED,
    COLOR_STEM_GENERATING,
    # Initialization
    init_state,
    init_banks,
    # Default data functions
    get_default_button_data,
    get_default_stems_data,
    ensure_stems_structure,
    # Getters
    get_root,
    get_bpm_lock_active,
    get_key_lock_active,
    get_multi_loop_active,
    get_master_bpm_value,
    get_master_volume,
    get_current_bank,
    get_speed_value,
    get_all_banks_data,
    get_button_data,
    get_buttons,
    get_bank_buttons,
    get_stem_indicators,
    get_loaded_loops,
    get_selected_stems_button,
    get_last_bpm_display,
    get_open_volume_windows,
    get_open_loop_editor_windows,
    get_save_config_timer,
    get_master_amp,
    # Setters
    set_button_data_ref,
    set_button_data_value,
    register_button,
    register_bank_button,
    register_stem_indicator,
    register_loaded_loop,
    unregister_loaded_loop,
    set_selected_stems_button,
    set_last_bpm_display,
    set_save_config_timer,
    set_master_amp,
    register_open_volume_window,
    unregister_open_volume_window,
    register_open_loop_editor_window,
    unregister_open_loop_editor_window,
)

__all__ = [
    # Constants
    'GRID_SIZE',
    'NUM_BANKS',
    'STEM_NAMES',
    'STEM_LABELS',
    'COLOR_BG',
    'COLOR_BTN_INACTIVE',
    'COLOR_BTN_ACTIVE',
    'COLOR_TEXT',
    'COLOR_TEXT_ACTIVE',
    'COLOR_LOCK_OFF',
    'COLOR_LOCK_ON',
    'COLOR_RESET_RED',
    'COLOR_BANK_BTN',
    'COLOR_BANK_ACTIVE',
    'COLOR_STEM_INACTIVE',
    'COLOR_STEM_AVAILABLE',
    'COLOR_STEM_SELECTED',
    'COLOR_STEM_GENERATING',
    # Initialization
    'init_state',
    'init_banks',
    # Default data functions
    'get_default_button_data',
    'get_default_stems_data',
    'ensure_stems_structure',
    # Getters
    'get_root',
    'get_bpm_lock_active',
    'get_key_lock_active',
    'get_multi_loop_active',
    'get_master_bpm_value',
    'get_master_volume',
    'get_current_bank',
    'get_speed_value',
    'get_all_banks_data',
    'get_button_data',
    'get_buttons',
    'get_bank_buttons',
    'get_stem_indicators',
    'get_loaded_loops',
    'get_selected_stems_button',
    'get_last_bpm_display',
    'get_open_volume_windows',
    'get_open_loop_editor_windows',
    'get_save_config_timer',
    'get_master_amp',
    # Setters
    'set_button_data_ref',
    'set_button_data_value',
    'register_button',
    'register_bank_button',
    'register_stem_indicator',
    'register_loaded_loop',
    'unregister_loaded_loop',
    'set_selected_stems_button',
    'set_last_bpm_display',
    'set_save_config_timer',
    'set_master_amp',
    'register_open_volume_window',
    'unregister_open_volume_window',
    'register_open_loop_editor_window',
    'unregister_open_loop_editor_window',
]
