"""Core module for flitzis_looper.

Contains state management, configuration, and core logic.
"""

# Import from submodules for re-export
from flitzis_looper.core.state import (
    COLOR_BANK_ACTIVE,
    COLOR_BANK_BTN,
    COLOR_BG,
    COLOR_BTN_ACTIVE,
    COLOR_BTN_INACTIVE,
    COLOR_LOCK_OFF,
    COLOR_LOCK_ON,
    COLOR_RESET_RED,
    COLOR_STEM_AVAILABLE,
    COLOR_STEM_GENERATING,
    COLOR_STEM_INACTIVE,
    COLOR_STEM_SELECTED,
    COLOR_TEXT,
    COLOR_TEXT_ACTIVE,
    # Constants
    GRID_SIZE,
    NUM_BANKS,
    STEM_LABELS,
    STEM_NAMES,
    ensure_stems_structure,
    get_all_banks_data,
    get_bank_buttons,
    get_bpm_lock_active,
    get_button_data,
    get_buttons,
    get_current_bank,
    # Default data functions
    get_default_button_data,
    get_default_stems_data,
    get_key_lock_active,
    get_last_bpm_display,
    get_loaded_loops,
    get_master_amp,
    get_master_bpm_value,
    get_master_volume,
    get_multi_loop_active,
    get_open_loop_editor_windows,
    get_open_volume_windows,
    # Getters
    get_root,
    get_save_config_timer,
    get_selected_stems_button,
    get_speed_value,
    get_stem_indicators,
    init_banks,
    # Initialization
    init_state,
    register_bank_button,
    register_button,
    register_loaded_loop,
    register_open_loop_editor_window,
    register_open_volume_window,
    register_stem_indicator,
    # Setters
    set_button_data_ref,
    set_button_data_value,
    set_last_bpm_display,
    set_master_amp,
    set_save_config_timer,
    set_selected_stems_button,
    unregister_loaded_loop,
    unregister_open_loop_editor_window,
    unregister_open_volume_window,
)

__all__ = [
    "COLOR_BANK_ACTIVE",
    "COLOR_BANK_BTN",
    "COLOR_BG",
    "COLOR_BTN_ACTIVE",
    "COLOR_BTN_INACTIVE",
    "COLOR_LOCK_OFF",
    "COLOR_LOCK_ON",
    "COLOR_RESET_RED",
    "COLOR_STEM_AVAILABLE",
    "COLOR_STEM_GENERATING",
    "COLOR_STEM_INACTIVE",
    "COLOR_STEM_SELECTED",
    "COLOR_TEXT",
    "COLOR_TEXT_ACTIVE",
    # Constants
    "GRID_SIZE",
    "NUM_BANKS",
    "STEM_LABELS",
    "STEM_NAMES",
    "ensure_stems_structure",
    "get_all_banks_data",
    "get_bank_buttons",
    "get_bpm_lock_active",
    "get_button_data",
    "get_buttons",
    "get_current_bank",
    # Default data functions
    "get_default_button_data",
    "get_default_stems_data",
    "get_key_lock_active",
    "get_last_bpm_display",
    "get_loaded_loops",
    "get_master_amp",
    "get_master_bpm_value",
    "get_master_volume",
    "get_multi_loop_active",
    "get_open_loop_editor_windows",
    "get_open_volume_windows",
    # Getters
    "get_root",
    "get_save_config_timer",
    "get_selected_stems_button",
    "get_speed_value",
    "get_stem_indicators",
    "init_banks",
    # Initialization
    "init_state",
    "register_bank_button",
    "register_button",
    "register_loaded_loop",
    "register_open_loop_editor_window",
    "register_open_volume_window",
    "register_stem_indicator",
    # Setters
    "set_button_data_ref",
    "set_button_data_value",
    "set_last_bpm_display",
    "set_master_amp",
    "set_save_config_timer",
    "set_selected_stems_button",
    "unregister_loaded_loop",
    "unregister_open_loop_editor_window",
    "unregister_open_volume_window",
]
