class AudioMessage:
    class Ping(AudioMessage):
        def __init__(self) -> None: ...

    class Pong(AudioMessage):
        def __init__(self) -> None: ...

    class Stopped(AudioMessage):
        def __init__(self) -> None: ...

class AudioEngine:
    def __init__(self) -> None: ...
    def run(self) -> None: ...
    def shut_down(self) -> None: ...
    def load_sample(self, sample_id: int, path: str) -> None: ...
    def play_sample(self, sample_id: int, velocity: float) -> None: ...
    def ping(self) -> None: ...
    def receive_msg(self) -> AudioMessage | None: ...
