class AudioMessage:
    def pad_peak(self) -> tuple[int, float] | None: ...

    class Pong(AudioMessage):
        def __init__(self) -> None: ...

    class Stopped(AudioMessage):
        def __init__(self) -> None: ...

    class PadPeak(AudioMessage):
        def __init__(self, pad_id: int, peak: float) -> None: ...

class AudioEngine:
    def __init__(self) -> None: ...
    def run(self) -> None: ...
    def shut_down(self) -> None: ...
    def load_sample_async(self, sample_id: int, path: str) -> None: ...
    def analyze_sample_async(self, sample_id: int) -> None: ...
    def poll_loader_events(self) -> dict[str, object] | None: ...
    def play_sample(self, sample_id: int, volume: float) -> None: ...
    def stop_sample(self, sample_id: int) -> None: ...
    def stop_all(self) -> None: ...
    def set_volume(self, volume: float) -> None: ...
    def set_speed(self, speed: float) -> None: ...
    def set_pad_gain(self, sample_id: int, gain: float) -> None: ...
    def set_pad_eq(self, sample_id: int, low_db: float, mid_db: float, high_db: float) -> None: ...
    def set_bpm_lock(self, enabled: bool) -> None: ...
    def set_key_lock(self, enabled: bool) -> None: ...
    def set_master_bpm(self, bpm: float) -> None: ...
    def set_pad_bpm(self, sample_id: int, bpm: float | None) -> None: ...
    def unload_sample(self, sample_id: int) -> None: ...
    def ping(self) -> None: ...
    def receive_msg(self) -> AudioMessage | None: ...
