import numpy as np
from numpy.typing import NDArray

class AudioMessage:
    def sample_id(self) -> int | None: ...
    def pad_peak(self) -> float | None: ...
    def pad_playhead(self) -> float | None: ...

    class Pong(AudioMessage):
        def __init__(self) -> None: ...

    class SampleStarted(AudioMessage):
        def __init__(self, pad_id: int) -> None: ...

    class SampleStopped(AudioMessage):
        def __init__(self, pad_id: int) -> None: ...

    class PadPeak(AudioMessage):
        def __init__(self, pad_id: int, peak: float) -> None: ...

    class PadPlayhead(AudioMessage):
        def __init__(self, pad_id: int, position_s: float) -> None: ...

class AudioEngine:
    def __init__(self) -> None: ...
    def run(self) -> None: ...
    def shut_down(self) -> None: ...
    def load_sample_async(self, sample_id: int, path: str, run_analysis: bool = True) -> None: ...
    def analyze_sample_async(self, sample_id: int) -> None: ...
    def poll_loader_events(self) -> dict[str, object] | None: ...
    def play_sample(self, sample_id: int, volume: float) -> None: ...
    def stop_sample(self, sample_id: int) -> None: ...
    def pause_sample(self, sample_id: int) -> None: ...
    def resume_sample(self, sample_id: int) -> None: ...
    def stop_all(self) -> None: ...
    def set_volume(self, volume: float) -> None: ...
    def set_speed(self, speed: float) -> None: ...
    def set_pad_gain(self, sample_id: int, gain: float) -> None: ...
    def set_pad_eq(self, sample_id: int, low_db: float, mid_db: float, high_db: float) -> None: ...
    def set_pad_loop_region(self, sample_id: int, start_s: float, end_s: float | None) -> None: ...
    def set_bpm_lock(self, enabled: bool) -> None: ...
    def set_key_lock(self, enabled: bool) -> None: ...
    def set_master_bpm(self, bpm: float) -> None: ...
    def set_pad_bpm(self, sample_id: int, bpm: float | None) -> None: ...
    def unload_sample(self, sample_id: int) -> None: ...
    def ping(self) -> None: ...
    def receive_msg(self) -> AudioMessage | None: ...
    def get_waveform_render_data(
        self, sample_id: int, width_px: int, start_s: float, end_s: float
    ) -> WaveFormRenderData | None: ...

type WaveFormRenderData = tuple[
    bool,  # True=raw mode; False=aggregate
    NDArray[np.float32],  # Time values
    NDArray[np.float32],  # y_min (or raw samples in raw mode)
    NDArray[np.float32] | None,  # y_max (or None if in raw mode)
]
